apiVersion: v1
kind: Namespace
metadata:
  name: dft-sdfgsdfg-dev
  labels:
    environment-id: env_1373a136-e564-4ba9-8b19-fd9eb7ea6da3
    project-id: project_4c1dee2c-959c-44c9-be2a-a3568363ea87
    project-name: dft sdfgsdfg
    environment-name: dev
    organization-id: org_c50d7b26-1f2a-4a6e-b11e-469a86e002c8
